# Generated by Django 3.1.5 on 2021-03-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='comments',
            new_name='general_comments',
        ),
        migrations.AddField(
            model_name='grade',
            name='creativity_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='educational_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='function_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='implementation_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='readability_comments',
            field=models.TextField(blank=True),
        ),
    ]
