# Generated by Django 3.1.5 on 2021-02-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_auto_20210212_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='design',
        ),
        migrations.AddField(
            model_name='grade',
            name='creativity',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='educational',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='implementation',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
