# Generated by Django 3.1.5 on 2021-03-06 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_auto_20210306_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('approved', models.BooleanField()),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.competitor')),
            ],
        ),
    ]
