# Generated by Django 3.1.5 on 2021-03-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_bonusimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusimage',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
