# Generated by Django 3.1.5 on 2021-03-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_auto_20210306_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'Closed'), ('O', 'Open'), ('E', 'Ended')], default='C', max_length=1)),
            ],
        ),
    ]
