# Generated by Django 3.1.5 on 2021-03-08 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='educational',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='educational_comments',
        ),
    ]
