# Generated by Django 3.1.5 on 2021-03-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0006_auto_20210308_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='school',
            field=models.CharField(default='Test HS', max_length=128),
            preserve_default=False,
        ),
    ]
